version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build_and_test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: python:3.10.8-slim-bullseye
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: pytest --no-migrations -W ignore::DeprecationWarning
      # - run:
      #     name: lint
      #     command: pylint my_media/ media_organizer/
      - run:
          name: lint app
          command: flake8
  contenerize:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t $DOCKERHUB_USERNAME/project13:CircleCI .
      - run: docker push $DOCKERHUB_USERNAME/project13:CircleCI
  # deploy:
  #   docker:
  #       - image: cimg/base:2022.06
  #         auth:
  #             username: $DOCKERHUB_USERNAME
  #             password: $DOCKERHUB_PASSWORD
  #   steps:
  #       - checkout
  #       - run:
  #           name: Deploy Master to Heroku
  #           command: |
  #             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  # version: 2
  build_test_contenerize_deploy:
    jobs:
      - build_and_test
      - contenerize:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: master # only deploy when on main
      - heroku/deploy-via-git:
          requires:
            - contenerize
          post-steps:
            - run: heroku python manage.py migrate
      # - deploy:
      #     requires:
      #       - contenerize